#
# General Dart project configuration
#
name: #{name}
description: #{description}
publish_to: 'none'
version: 1.0.0+1

environment:
  flutter: ^2.0.3
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  device_info: ^2.0.0
  flutter:
    sdk: flutter
  json_annotation: ^4.0.1
  package_info: ^2.0.0
  path_provider: ^2.0.1
  protobuf: ^2.0.0 #{pb_line}
  shared_preferences: ^2.0.5
  uri: ^1.0.0
  url_launcher: ^6.0.3

dev_dependencies:
  build_runner: ^1.12.2
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.0
  mockito: ^5.0.3

#
# Flutter and package-specific configuration
#
flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/icon-adaptive-bg.png"
  adaptive_icon_foreground: "assets/launcher/icon-adaptive.png"
