#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

project_root=$(dirname "${BASH_SOURCE[@]}")

echo -n "Project Name: "
read -r project_name
echo -n "Bundle Prefix (e.g. com.example): "
read -r project_prefix
echo -n "Description (optional): "
read -r project_description
echo -n ".proto directory (optional): "
read -r protobuf_source

rm -rf "$project_root/android/app/src/main/kotlin/com/example"
mv pubspec.yaml template.pubspec.yaml

flutter create --project-name "$project_name" \
  --org "$project_prefix" \
  --description "$project_description" \
  --overwrite \
  "$project_root"

sed -i '' "s/#{name}/$project_name/" template.pubspec.yaml
sed -i '' "s/#{description}/$project_description/" template.pubspec.yaml
mv template.pubspec.yaml pubspec.yaml

if [[ -n "$protobuf_source" ]]; then
  sed -i '' "s,#{pb_line},," Makefile
  sed -i '' "s,#{pb_source},$protobuf_source," Makefile
else
  sed -i '' "s,.*#{pb_.*,," Makefile
fi

mkdir -p assets lib/screens lib/components lib/gen lib/state test_driver

git remote add upstream git@github.com:ActionSprout/flutter-app-template.git
git lfs install
git lfs track "*.gif" "*.jpg" "*.png" "*.ttf"
git add "$project_root"

cat <<EOF
To finish setting up, review the changes the start_here script has made
(git diff --cached), and update source control.

The project template has been added as the "upstream" git remote. To update
this project in the future, pull the latest and merge as necessary (git pull upstream master).
EOF
